name: Python Service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  build:

    runs-on: ubuntu-latest #构建环境，如无特殊需要可以默认为ubuntu-latest

    steps:  # 步骤
    - uses: actions/checkout@v1    # 注释1
    - name: Set up Python 3.7      # 使用python特定版本
      uses: actions/setup-python@v1
      with:
        python-version: 3.7        # 注释2
    - name: Build
      run: |
        python ./vmess.py

    - name: commit
      run: |
        git config --global user.email wodeupan1@163.com
        git config --global user.name wodeupan1
        git add .
        git commit -m "update" -a
		
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.vmess_decode }}
